




const arrListJarsName = [






	{ id: '_7up' 					, title: '7up' 					, } ,
	{ id: 'a_le_coq' 				, title: 'A.LeCoq' 				, } ,
	{ id: 'adrenalin' 				, title: 'Adrenalin' 			, } ,
	{ id: 'arizona' 				, title: 'AriZona' 				, } ,
	{ id: 'b52' 					, title: 'B52' 					, } ,
	{ id: 'barr' 					, title: 'Barr' 				, } ,
	{ id: 'bakalar' 				, title: 'Bakalar' 				, } ,
	{ id: 'baltika' 				, title: 'Baltika' 				, } ,
	{ id: 'battery' 				, title: 'Battery' 				, } ,
	{ id: 'bavaria' 				, title: 'Bavaria' 				, } ,
	{ id: 'brewdog' 				, title: 'Brewdog' 				, } ,
	{ id: 'bellini' 				, title: 'Bellini' 				, } ,
	{ id: 'best_shot' 				, title: 'Best Shot' 			, } ,
	{ id: 'bitburger' 				, title: 'Bitburger' 			, } ,
	{ id: 'black' 					, title: 'Black' 				, } ,
	{ id: 'bomba' 					, title: 'Bomba B!' 			, } ,
	{ id: 'bos' 					, title: 'Bos' 					, } ,
	{ id: 'bud' 					, title: 'Bbud' 				, } ,
	{ id: 'budvar' 					, title: 'Budvar' 				, } ,
	{ id: 'bum_bum' 				, title: 'Bum Bum' 				, } ,
	{ id: 'burn' 					, title: 'Burn' 				, } ,
	{ id: 'canada_dry' 				, title: 'Canada Dry' 			, } ,
	{ id: 'carlsberg' 				, title: 'Carlsberg' 			, } ,
	{ id: 'charlies' 				, title: 'Charlies' 			, } ,
	{ id: 'chupa_chups' 			, title: 'Chupa Chups' 			, } ,
	{ id: 'clausthaler' 			, title: 'Clausthaler' 			, } ,
	{ id: 'coca_cola' 				, title: 'Coca Cola' 			, } ,
	{ id: 'coffee' 					, title: 'Coffee' 				, } ,
	{ id: 'cola' 					, title: 'Cola' 				, } ,
	{ id: 'cola_vegan' 				, title: 'Cola Vegan' 			, } ,
	{ id: 'cortes' 					, title: 'Cortes' 				, } ,
	{ id: 'double_seven' 			, title: 'Double Seven' 		, } ,
	{ id: 'douwe_egberts' 			, title: 'Douwe Egberts' 		, } ,
	{ id: 'dr_pepper' 				, title: 'Dr Pepper' 			, } ,
	{ id: 'edelmeister' 			, title: 'Edelmeister' 			, } ,
	{ id: 'estrella_galicia' 		, title: 'Estrella Galicia' 	, } ,
	{ id: 'ever' 					, title: 'Ever AID+' 			, } ,
	{ id: 'evolution' 				, title: 'Evolution' 			, } ,
	{ id: 'fanta' 					, title: 'Fanta' 				, } ,
	{ id: 'faxe' 					, title: 'Faxe' 				, } ,
	{ id: 'feldschloesschen' 		, title: 'Feldschloesschen' 	, } ,
	{ id: 'fentimans' 				, title: 'Fentimans' 			, } ,
	{ id: 'fragolino' 				, title: 'Fragolino' 			, } ,
	{ id: 'free_damm' 				, title: 'Free Damm' 			, } ,
	{ id: 'freego' 					, title: 'Freego' 				, } ,
	{ id: 'frugo' 					, title: 'Frugo' 				, } ,
	{ id: 'g_energy' 				, title: 'G-Energy' 			, } ,
	{ id: 'garage' 					, title: 'Garage' 				, } ,
	{ id: 'geyser' 					, title: 'Geyser' 				, } ,
	{ id: 'go' 						, title: 'Go' 					, } ,
	{ id: 'gorilla' 				, title: 'Gorilla' 				, } ,
	{ id: 'gosser' 					, title: 'Gosser' 				, } ,
	{ id: 'green_energy' 			, title: 'Green Energy' 		, } ,
	{ id: 'grotwerg' 				, title: 'Grotwerg' 			, } ,
	{ id: 'guarana' 				, title: 'Guarana' 				, } ,
	{ id: 'gubernija' 				, title: 'Gubernija' 			, } ,
	{ id: 'heineken' 				, title: 'Heineken' 			, } ,
	{ id: 'hell' 					, title: 'Hell' 				, } ,
	{ id: 'hike' 					, title: 'Hike' 				, } ,
	{ id: 'hoegaarden' 				, title: 'Hoegaarden' 			, } ,
	{ id: 'ice_cool' 				, title: 'Ice Cool' 			, } ,
	{ id: 'irn_bru' 				, title: 'Irn Bru' 				, } ,
	{ id: 'iron' 					, title: 'Iron' 				, } ,
	{ id: 'jacobs' 					, title: 'Jacobs' 				, } ,
	{ id: 'jaguar' 					, title: 'Jaguar' 				, } ,
	{ id: 'jaguaro' 				, title: 'Jaguaro' 				, } ,
	{ id: 'jaffa' 					, title: 'Jaffa' 				, } ,
	{ id: 'johan_freitag' 			, title: 'Johan Freitag' 		, } ,
	{ id: 'jett' 					, title: 'Dжетт' 				, } ,
	{ id: 'kaiserdom' 				, title: 'Kaiserdom' 			, } ,
	{ id: 'kalnapilis' 				, title: 'Kalnapilis' 			, } ,
	{ id: 'keten_brug' 				, title: 'Keten Brug' 			, } ,
	{ id: 'kok' 					, title: 'Kok' 					, } ,
	{ id: 'komodo' 					, title: 'Komodo' 				, } ,
	{ id: 'kozel' 					, title: 'Kozel' 				, } ,
	{ id: 'krombacher' 				, title: 'Krombacher' 			, } ,
	{ id: 'kronenbourg' 			, title: 'Kronenbourg' 			, } ,
	{ id: 'krusovice' 				, title: 'Krusovice' 			, } ,
	{ id: 'lacplesis' 				, title: 'Lacplesis' 			, } ,
	{ id: 'lander_brau' 			, title: 'Lander Brau' 			, } ,
	{ id: 'lomza_radler' 			, title: 'Lomza Radler' 		, } ,
	{ id: 'lipton' 					, title: 'Lipton' 				, } ,
	{ id: 'leffe' 					, title: 'Leffe' 				, } ,
	{ id: 'lemonade_joe' 			, title: 'Lemonade Joe' 		, } ,
	{ id: 'lowenbrau' 				, title: 'Lowenbrau' 			, } ,
	{ id: 'maaza' 					, title: 'Maaza' 				, } ,
	{ id: 'meister' 				, title: 'Meister' 				, } ,
	{ id: 'minions' 				, title: 'Minions' 				, } ,
	{ id: 'mirinda' 				, title: 'Mirinda' 				, } ,
	{ id: 'mojito' 					, title: 'Mojito' 				, } ,
	{ id: 'molecola' 				, title: 'Molecola' 			, } ,
	{ id: 'monster' 				, title: 'Monster' 				, } ,
	{ id: 'mountain_dew' 			, title: 'Mountain Dew' 		, } ,
	{ id: 'ngine' 					, title: 'Ngine' 				, } ,
	{ id: 'nescafe' 				, title: 'Nescafe' 				, } ,
	{ id: 'non_stop' 				, title: 'Non Stop' 			, } ,
	{ id: 'no_worries' 				, title: 'No Worries' 			, } ,
	{ id: 'oettinger' 				, title: 'Oettinger' 			, } ,
	{ id: 'opillia' 				, title: 'Opillia' 				, } ,
	{ id: 'oshee' 					, title: 'Oshee' 				, } ,
	{ id: 'pepsi' 					, title: 'Pepsi' 				, } ,
	{ id: 'perrier' 				, title: 'Perrier' 				, } ,
	{ id: 'pfanner' 				, title: 'Pfanner' 				, } ,
	{ id: 'pit_ballert' 			, title: 'Pit Ballert' 			, } ,
	{ id: 'pit_bull' 				, title: 'Pit Bull' 			, } ,
	{ id: 'power' 					, title: 'Power' 				, } ,
	{ id: 'primator' 				, title: 'Primator' 			, } ,
	{ id: 'pulls' 					, title: 'Pulls' 				, } ,
	{ id: 'pulse' 					, title: 'Pulse' 				, } ,
	{ id: 'r_whtes' 				, title: 'R Whtes' 				, } ,
	{ id: 'red_bull' 				, title: 'Red Bull' 			, } ,
	{ id: 'regenera' 				, title: 'Regenera' 			, } ,
	{ id: 'ritterburg' 				, title: 'Ritterburg' 			, } ,
	{ id: 'roar' 					, title: 'Roar' 				, } ,
	{ id: 'rockstar_refresh' 		, title: 'Rockstar Refresh' 	, } ,
	{ id: 'royal_club' 				, title: 'Royal Club' 			, } ,
	{ id: 'rubicon' 				, title: 'Rubicon' 				, } ,
	{ id: 'sanpellegrino' 			, title: 'Sanpellegrino' 		, } ,
	{ id: 'schweppes' 				, title: 'Schweppes' 			, } ,
	{ id: 'schlitz' 				, title: 'Schlitz' 				, } ,
	{ id: 'schwip_schwap' 			, title: 'Schwip Schwap' 		, } ,
	{ id: 'sherwood' 				, title: 'Sherwood' 			, } ,
	{ id: 'sinkist' 				, title: 'Sinkist' 				, } ,
	{ id: 'sprite' 					, title: 'Sprite' 				, } ,
	{ id: 'stammgast' 				, title: 'Stammgast' 			, } ,
	{ id: 'stella_artois' 			, title: 'Stella Artois' 		, } ,
	{ id: 'stumble_guys' 			, title: 'Stumble Guys' 		, } ,
	{ id: 'svijany' 				, title: 'Svijany' 				, } ,
	{ id: 'tango' 					, title: 'Tango' 				, } ,
	{ id: 'tauras' 					, title: 'Tauras' 				, } ,
	{ id: 'tuborg' 					, title: 'Tuborg' 				, } ,
	{ id: 'ukie' 					, title: 'Ukie' 				, } ,
	{ id: 'vinut' 					, title: 'Vinut' 				, } ,
	{ id: 'vitamin' 				, title: 'Vitamin' 				, } ,
	{ id: 'volfas' 					, title: 'Volfas' 				, } ,
	{ id: 'xixo' 					, title: 'Xixo' 				, } ,
	{ id: 'zibert' 					, title: 'Zibert' 				, } ,
	{ id: 'zipfer' 					, title: 'Zipfer' 				, } ,
	{ id: 'warheads' 				, title: 'WarHeads' 			, } ,
	{ id: '_0_non_alco' 			, title: '0 Non Alcoholic' 		, } ,
	{ id: '_1_priv_brov' 			, title: '1 Приватна Броварня' 	, } ,
	{ id: 'bile' 					, title: 'Біле' 				, } ,
	{ id: 'vyatrachok' 				, title: 'Вятрачок' 			, } ,
	{ id: 'zhivchik' 				, title: 'Живчик' 				, } ,
	{ id: 'zakarpatske' 			, title: 'Закарпатське' 		, } ,
	{ id: 'lymonady_cherkaschyny' 	, title: 'Лимонади Черкащини' 	, } ,
	{ id: 'lvivske' 				, title: 'Львівське' 			, } ,
	{ id: 'pivovarnya_n1' 			, title: 'Пивоварня №1' 		, } ,
	{ id: 'rozmay_lisovy' 			, title: 'Розмай лісовий' 		, } ,
	{ id: 'chayka' 					, title: 'Чайка ' 				, } ,
	{ id: 'chernigivske' 			, title: 'Чернігівське ' 		, } ,

	{ id: 'kvass' 					, title: 'Квас' 				, } ,
	{ id: 'kvass_premium' 			, title: '- Kvass Premium' 		, } ,
	{ id: 'kvass_tail' 				, title: '- Kvastail' 			, } ,
	{ id: 'kvass_kyivsky' 			, title: '- Квас Київський' 	, } ,
	{ id: 'kvass_opillia' 			, title: '- Квас Опілля' 		, } ,
	{ id: 'kvass_taras' 			, title: '- Квас Тарас' 		, } ,



];












